import { Metadata } from "next";
import Navigation from "../components/navigation";

export const metadata: Metadata = {
  title: {
    template: '%s | NestJS',
    default: "제목 없음",
  },
  description: 'Generated by Next.js'
}

export default function Layout ({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
