import { Metadata } from "next";
import Navigation from "../components/navigation";
import Footer from "../components/footer/footer";
import '../styles/global.css';

export const metadata: Metadata = {
  title: {
    template: '%s | NestJS',
    default: "Nest Movies",
  },
  description: 'Generated by Next.js'
}

export default function Layout ({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ko'>
      <body suppressHydrationWarning={true}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
